//! Independently reviewed semantic anchors, not imported from the runner.
//! Changing these is a change to the readiness contract, not discovery.

pub const TARGETS: [&str; 4] = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
];
pub const CHANNELS: [&str; 4] = [
    "candidate-native",
    "candidate-cargo",
    "public-native",
    "public-cargo",
];
pub const PRODUCER_JOBS: [(&str, &str); 4] = [
    ("x86_64-unknown-linux-gnu", "linux-x64"),
    ("aarch64-unknown-linux-gnu", "linux-arm64"),
    ("x86_64-pc-windows-msvc", "windows-x64"),
    ("aarch64-pc-windows-msvc", "windows-arm64"),
];
pub const REQUIREMENTS: [&str; 14] = [
    "CR-01", "CR-02", "CR-03", "CR-04", "CR-05", "CR-06", "CR-07", "CR-08", "CR-09", "CR-10",
    "CR-11", "CR-12", "CR-13", "CR-14",
];

// family, platform, evidence class, complete finite scenarios, requirement crosswalk.
// This list is intentionally independent of the production manifest parser and
// expected-ledger generator. Coordinated manifest/result omissions still fail.
pub const CASES: &[(&str, &str, &str, &str, &str)] = &[
    (
        "C-PACKAGE",
        "both",
        "installed_product",
        "fresh-install verify upgrade final-uninstall",
        "CR-02 CR-04 CR-13",
    ),
    (
        "C-IO",
        "both",
        "installed_product",
        "empty-input empty-message binary-streams binary-file native-argv bounded-large-output",
        "CR-01 CR-06 CR-07",
    ),
    (
        "C-STATUS",
        "both",
        "installed_product",
        "zero nonzero exit-123 exit-124 exit-125 exit-126 exit-127 deadline memory",
        "CR-08 CR-09",
    ),
    (
        "C-ADMISSION",
        "both",
        "installed_product",
        "positive unsupported-request stale-grant wrong-caller",
        "CR-09 CR-10",
    ),
    (
        "C-LIFETIME",
        "both",
        "installed_product",
        "root-first frontend-loss guardian-loss service-loss worker-loss recovery",
        "CR-04 CR-08",
    ),
    (
        "C-PARSER",
        "both",
        "installed_product",
        "valid-current-result",
        "CR-09",
    ),
    (
        "C-PARSER",
        "both",
        "native_component_regression",
        "duplicate-key wrong-format wrong-revision unknown-authority-variant oversized-record stale-attempt wrong-product omitted-case duplicate-case forged-cleanup",
        "CR-01 CR-09",
    ),
    (
        "L-MIX-01",
        "linux",
        "installed_product",
        "joint-build-tcp-unix-http",
        "CR-05 CR-06",
    ),
    (
        "L-MIX-02",
        "linux",
        "installed_product",
        "endpoint-mismatch",
        "CR-05",
    ),
    (
        "L-MIX-03",
        "linux",
        "installed_product",
        "listener-and-file-transfer",
        "CR-05 CR-10",
    ),
    (
        "L-MIX-04",
        "linux",
        "installed_product",
        "cooperation cross-attempt",
        "CR-05 CR-10",
    ),
    (
        "L-MIX-05",
        "linux",
        "installed_product",
        "empty-input empty-message binary-streams bounded-large-output",
        "CR-05 CR-06",
    ),
    (
        "L-ISO-01",
        "linux",
        "installed_product",
        "host-tcp nonloopback ipv6 udp raw packet netlink",
        "CR-10",
    ),
    (
        "L-ISO-02",
        "linux",
        "installed_product",
        "host-run-socket host-temp-socket input-socket imported-socket caller-writable-tree",
        "CR-10",
    ),
    (
        "L-ISO-03",
        "linux",
        "installed_product",
        "host-abstract other-attempt-abstract own-abstract-positive",
        "CR-05 CR-10",
    ),
    (
        "L-ISO-04",
        "linux",
        "installed_product",
        "symlink dotdot proc-root proc-cwd proc-fd opath hardlink mount-alias",
        "CR-10",
    ),
    (
        "L-ISO-05",
        "linux",
        "installed_product",
        "stdio-host-socket extra-host-fd pidfd-getfd ptrace namespace-entry",
        "CR-10",
    ),
    (
        "L-ISO-06",
        "linux",
        "installed_product",
        "same-uid-process account-alias stale-reservation",
        "CR-06 CR-10",
    ),
    (
        "L-IMG-01",
        "linux",
        "installed_product",
        "first-image interpreter shared-library writable-alias",
        "CR-06 CR-10",
    ),
    (
        "L-IMG-02",
        "linux",
        "installed_product",
        "ld-injection rpath-injection loader-config",
        "CR-06 CR-10",
    ),
    (
        "L-IMG-03",
        "linux",
        "installed_product",
        "dynamic-rust-build-and-exec image-only-entrypoint",
        "CR-06",
    ),
    (
        "L-IMG-04",
        "linux",
        "installed_product",
        "export-symlink export-fifo export-device export-socket export-traversal export-concurrent-writer",
        "CR-08 CR-10",
    ),
    (
        "L-ID-01",
        "linux",
        "installed_product",
        "delegated-final-credentials generated-descendants v1-preserve-caller v2-preserve-caller",
        "CR-06",
    ),
    (
        "L-ID-02",
        "linux",
        "installed_product",
        "wrong-caller wrong-plan wrong-image wrong-profile wrong-identity wrong-digest wrong-epoch disabled-grant changed-grant v3-preserve-caller",
        "CR-06 CR-09 CR-10",
    ),
    (
        "L-ID-03",
        "linux",
        "installed_product",
        "revoke-discovery revoke-preparation revoke-release drain-running revoke-running restart-fresh-admission",
        "CR-08 CR-10",
    ),
    (
        "L-LIFE-01",
        "linux",
        "installed_product",
        "root-first-resource-descendant",
        "CR-08",
    ),
    (
        "L-LIFE-02",
        "linux",
        "installed_product",
        "frontend-allocation frontend-release frontend-drain worker-allocation worker-release worker-drain guardian-allocation guardian-release guardian-drain control-allocation control-release control-drain",
        "CR-08",
    ),
    (
        "L-LIFE-03",
        "linux",
        "installed_product",
        "deadline memory cancellation reserved-target-exit",
        "CR-08 CR-09",
    ),
    (
        "L-LIFE-04",
        "linux",
        "native_component_regression",
        "crash-before-account-retirement lost-terminal-response",
        "CR-08 CR-09",
    ),
    (
        "L-LIFE-05",
        "linux",
        "installed_product",
        "report-persistence-failure relay-backpressure",
        "CR-08",
    ),
    (
        "L-VER-01",
        "linux",
        "installed_product",
        "old-provider v3-result-v1 unknown-request-variant duplicate-request corrupted-binding",
        "CR-09",
    ),
    (
        "L-VER-01",
        "linux",
        "native_component_regression",
        "v1-vectors v2-vectors v3-vectors filter-x64 filter-arm64 projection-mutation release-barrier journal-barrier",
        "CR-09 CR-10",
    ),
    (
        "W-PACKAGE",
        "windows",
        "installed_product",
        "materialize install verify component-measure",
        "CR-02 CR-04 CR-13",
    ),
    (
        "W-ENVELOPE",
        "windows",
        "installed_product",
        "ordinary restricted sentinel-handles",
        "CR-07 CR-10",
    ),
    (
        "W-ENVELOPE",
        "windows",
        "native_component_regression",
        "remove-creation-job remove-suspended-check replace-token broaden-handle-list",
        "CR-07 CR-10",
    ),
    (
        "W-JOINT",
        "windows",
        "installed_product",
        "ordinary restricted endpoint-mismatch",
        "CR-07 CR-10",
    ),
    (
        "W-TOOLCHAIN",
        "windows",
        "installed_product",
        "ordinary restricted",
        "CR-07",
    ),
    (
        "W-IO",
        "windows",
        "installed_product",
        "empty-stdout-stderr empty-message embedded-nul all-bytes invalid-utf8 final-fragment backpressure-separated-streams empty-file binary-file argv-empty argv-whitespace argv-quotes argv-backslashes argv-unicode argv-path argv-nul-rejection",
        "CR-07 CR-09",
    ),
    (
        "W-CHURN",
        "windows",
        "installed_product",
        "natural-4096-three-generations",
        "CR-07 CR-08",
    ),
    (
        "W-POPULATION",
        "windows",
        "installed_product",
        "held-257-deadline",
        "CR-08",
    ),
    (
        "W-DESCENDANT",
        "windows",
        "installed_product",
        "root-first intermediate-parent-first nested-job breakaway-denial allowed-token-change",
        "CR-07 CR-08 CR-10",
    ),
    (
        "W-STATUS",
        "windows",
        "installed_product",
        "zero nonzero exit-123 exit-124 exit-125 exit-126 exit-127 target-failure admission-refusal deadline memory",
        "CR-08 CR-09",
    ),
    (
        "W-CAPACITY",
        "windows",
        "installed_product",
        "serial-retirement bounded-concurrency fresh-positive-after-recovery",
        "CR-07 CR-08",
    ),
    (
        "W-CAUSAL",
        "windows",
        "installed_product",
        "known-guardian-original",
        "CR-08 CR-09",
    ),
    (
        "W-CAUSAL",
        "windows",
        "native_component_regression",
        "receiptless-first-cause preauthorization postresume cleanup after-exit native-code-capture",
        "CR-08 CR-09",
    ),
    (
        "W-GUARDIAN",
        "windows",
        "installed_product",
        "after-release",
        "CR-08",
    ),
    (
        "W-REPLAY",
        "windows",
        "installed_product",
        "public-recovery-after-loss",
        "CR-08 CR-09",
    ),
    (
        "W-REPLAY",
        "windows",
        "native_component_regression",
        "durable-replay lost-publication-response lost-acknowledgement crash-before-durable crash-after-durable expiry-authority",
        "CR-08 CR-09",
    ),
    (
        "W-WRITER",
        "windows",
        "native_component_regression",
        "frozen-live serialization-error write-error rename-error readback-error crash-before-durable crash-after-durable settlement-reservation",
        "CR-08 CR-09",
    ),
    (
        "W-BINDING",
        "windows",
        "installed_product",
        "component-substitution unsupported-public-request stale-policy-epoch revoked-grant wrong-authorized-caller",
        "CR-09 CR-10 CR-13",
    ),
    (
        "W-BINDING",
        "windows",
        "native_component_regression",
        "caller-substitution attempt-substitution request-substitution generation-substitution receiptless-posttarget seed-replacement proof-mismatch projection-bounds",
        "CR-09 CR-10",
    ),
    (
        "W-RETIREMENT",
        "windows",
        "installed_product",
        "natural frontend-loss control-service-loss attempt-worker-loss output-backpressure",
        "CR-08",
    ),
    (
        "W-UPGRADE",
        "windows",
        "installed_product",
        "recover fresh-positive upgrade verify uninstall",
        "CR-04 CR-07 CR-13",
    ),
];
